
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Elite Tournament",
  description: "Generated by Anand",
};


  

export default function RootLayout({ children }) {
    
 
  return (
    <html lang="en">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
        {/* 1. Navigation Bar 
              // components/Navbar.jsx*/}
     <Navbar/>
        {children}
      </body>
    </html>
  );

}